### ISSUE TITLE
nulltranslate has no "context" argument

### ISSUE THREAD

**Issue by zjs2k** [collective/cioppino.twothumbs#24]
Commit 740f298 changed browser/like.py file so that the "context" is passed to translator instead of "target_language". But the nulltranslator isn't updated to include "context" argument (line 121). It will break if no translator found. Please simply add it to the function like this:
def nulltranslate(msgid, target_language=None, context=None):

Thank you!

**Comment by mauritsvanrees** [comment]
I have a fix ready and will make a PR.

But two questions (which may not be useful anymore, but I am curious):

How can I reproduce this? I tried setting a language (Afrikaans) for the site which has no translations for this add-on, and clicked a Like button, but that did not trigger it.

What happens in this case?  Do you have a Python traceback? That always helps.

**Comment by zjs2k** [comment]
Thank you very much for the quick fix. Here is the trackback:

`2019-10-08 20:52:04 ERROR Zope.SiteErrorLog 1570582324.160.380038620248 http://localhost:7070/Plone/front-page/you-know-you-like-it
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module cioppino.twothumbs.browser.like, line 101, in __call__
TypeError: nulltranslate() got an unexpected keyword argument 'context'
> /home/home/Plone/.buildout/eggs/cioppino.twothumbs-2.1.2-py2.7.egg/cioppino/twothumbs/browser/like.py(101)__call__()
-> context=self.request
(Pdb) 
`

I am running Plone 5.1.5:
`    Plone 5.1.5 (5115)
    CMF 2.2.12
    Zope 2.13.27
    Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
    PIL 5.2.0 (Pillow)
`

For me, no matter what language I switch to (Afrikanns or en-ca), I always get the error. This is not a fresh installation and has my own content type. But I just add "twothumbs" behavior to default "Page" type to activate the vote to the front-page.

Thanks again!

**Comment by mauritsvanrees** [comment]
I have merged the fix.

**Comment by mauritsvanrees** [comment]
I have released `cioppino.twothumbs 2.2.0` with the fix.
