### ISSUE TITLE
upgradeSteps don't match any metadata version

### ISSUE THREAD

**Issue by zjs2k** [collective/cioppino.twothumbs#31]
The upgradeSteps in configure.zcml is from 1000 to 1001. But the metadata.xml has version from 1 to 2 (1.2 in base profile). So the upgrade in the control panel doesn't do anything.

I would like to suggest two things: first, change the metadata.xml to 1001. Second, the upgrade should also include plone5 profile's plone.app.registry to install the js and css.

This bug is not essential mostly due to the upgrade as a one-time thing. I can do the upgrade in my own buildout package. But it may confuse new users who wants to do the upgrade.

**Comment by mauritsvanrees** [comment]
Two and a half years later... Sorry.

I was the one who added the upgrade step to 1001. I don't know what I was thinking.
Your suggestions make sense. I have added them in PR #36. Can you try it?

**Comment by zjs2k** [comment]
It's exactly what I did in my private branch. I assume it's no big deal considering all new users will be in the latest version. But thanks for the update.
Jay
    On Thursday, June 23, 2022, 05:49:48 PM EDT, Maurits van Rees ***@***.***> wrote:  
 
 


Two and a half years later... Sorry.

I was the one who added the upgrade step to 1001. I don't know what I was thinking.
Your suggestions make sense. I have added them in PR #36. Can you try it?
